title: Agency - Start Bootstrap Theme
description: ''
author: ''

sass:
  style: compressed

assets_path: '' 

collections:
  projects:

analytics:
  google: # UA-#########-#
# nav-theme: # dark or light
